---
- name: install open-vm-tools
  yum:
    name: '{{ cos7_openvmtools.package }}'
    state: present

- name: enable vmtoolsd and ensure it has started
  service:
    name: '{{ cos7_openvmtools.service }}'
    enabled: yes
    state: started
