---
- name: install open-vm-tools
  yum:
    name: '{{ deb8_openvmtools.package }}'
    state: present

- name: enable and restart vmtoolsd
  service:
    name: '{{ deb8_openvmtools.service }}'
    enabled: yes
    state: restarted
