---
- name: install open-vm-tools
  yum:
    name: '{{ item.package }}'
    state: present
  with_items: '{{ cos7_openvmtools }}'
- name: enable and restart vmtoolsd
  service:
    name: vmtoolsd
    enabled: yes
    state: restarted
...

