---

- name: install packages
  yum:
    name: "{{ openvmtools_packages }}"
    state: present

- name: enable and restart vmtoolsd
  service:
    name: vmtoolsd
    enabled: yes
    state: restarted
...

